import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Client} from './auth.mjs';
const base = process.env.API_URL ?? 'http://127.0.0.1:5080';
const manifest = JSON.parse(await readFile('artifacts/dicom-fixtures/manifest.json', 'utf8'));
const [first, second, wrong] = manifest;
const scheduler = await new Client().login();
const start = new Date(Date.UTC(2045, 0, 1) + Math.floor(Math.random()*100000)*900000);
const created = await scheduler.request('/api/appointments', {patientId:1,resourceId:1,startUtc:start.toISOString(),endUtc:new Date(+start+900000).toISOString()},crypto.randomUUID());
assert.equal(created.status,200);
const id=created.body.id, root=`/api/imaging/${id}`;
const cookie=[...scheduler.cookies].map(([k,v])=>`${k}=${v}`).join('; ');
assert.equal((await new Client().request(root+'/')).status,401);
const admin=await new Client().login('admin');
assert.equal((await admin.request(root+'/')).status,403);
const booker=new Client(); await booker.csrf();
assert.equal((await booker.request('/api/auth/register',{username:'img'+crypto.randomUUID().slice(0,12).replaceAll('-',''),password:'TestAccount123!',displayName:'Imaging test'})).status,201);
await booker.csrf();
assert.equal((await booker.request(root+'/')).status,403);
const search=await scheduler.request(root+'/search');
assert.equal(search.status,200,JSON.stringify(search));
assert.deepEqual(search.body.items.map(x=>x.studyInstanceUid).sort(),[first,second].map(x=>x.studyInstanceUid).sort());
assert.equal((await scheduler.request(root+'/links',{studyInstanceUid:wrong.studyInstanceUid})).body.code,'imaging_identity_mismatch');
assert.equal((await scheduler.request(root+'/links',{studyInstanceUid:first.studyInstanceUid})).status,204);
assert.equal((await scheduler.request(root+'/links',{studyInstanceUid:first.studyInstanceUid})).body.code,'imaging_duplicate');
assert.equal((await scheduler.request(root+'/links',{studyInstanceUid:second.studyInstanceUid})).status,204);
const data=await scheduler.request(root+`/studies/${first.studyInstanceUid}/metadata`);
assert.equal(data.body.length,6);
assert.equal(new Set(data.body.map(x=>x.seriesInstanceUid)).size,2);
const studyRoot=root+`/studies/${first.studyInstanceUid}`;
let response=await fetch(base+studyRoot+`/series/${first.seriesInstanceUid}/instances/${first.sopInstanceUid}/file`,{headers:{Cookie:cookie}});
assert.equal(response.status,200);
const bytes=Buffer.from(await response.arrayBuffer());
assert.equal(bytes.subarray(128,132).toString(),'DICM');
assert.equal(response.headers.get('cache-control'),'no-store');
response=await fetch(base+studyRoot+'/viewer/index.html?study='+first.studyInstanceUid,{headers:{Cookie:cookie}});
assert.equal(response.status,200);
assert.ok((await response.text()).includes('stone.js'));
response=await fetch(base+studyRoot+'/dicom-web/studies/'+wrong.studyInstanceUid+'/metadata',{headers:{Cookie:cookie}});
assert.equal(response.status,403);
response=await fetch(base+studyRoot+'/dicom-web/studies?StudyInstanceUID='+wrong.studyInstanceUid,{headers:{Cookie:cookie}});
assert.equal(response.status,403);
for (const resource of ['studies','series','instances']) {
  response=await fetch(base+studyRoot+'/dicom-web/'+resource+'?0020000D='+wrong.studyInstanceUid+'&0020000E='+first.seriesInstanceUid,{headers:{Cookie:cookie}});
  assert.equal(response.status,403);
}
response=await fetch(base+studyRoot+'/dicom-web/series?0020000D='+first.studyInstanceUid,{headers:{Cookie:cookie}});
assert.equal(response.status,200);
assert.equal((await response.json()).length,2);
response=await fetch(base+studyRoot+'/dicom-web/instances?0020000D='+first.studyInstanceUid+'&0020000E='+first.seriesInstanceUid,{headers:{Cookie:cookie}});
assert.equal(response.status,200);
assert.equal((await response.json()).length,3);
assert.equal((await booker.request(studyRoot+'/viewer/configuration.json')).status,403);
assert.equal((await booker.request(studyRoot+'/metadata')).status,403);
const operator=await new Client().login('taskoperator');
assert.equal((await operator.request(root+'/')).status,200);
const noCsrf=await fetch(base+root+`/links/${first.studyInstanceUid}/remove`,{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json'},body:'{}'});
assert.equal(noCsrf.status,400);
assert.equal((await operator.request(root+`/links/${first.studyInstanceUid}/remove`,{})).status,204);
assert.equal((await scheduler.request(studyRoot+'/metadata')).status,404);
assert.equal((await scheduler.request(studyRoot+'/viewer/configuration.json')).status,404);
const state=(await scheduler.request(root+'/')).body;
assert.equal(state.links.length,1);
assert.equal(state.audit.length,3);
assert.ok(state.audit.every(x=>x.correlationId));
console.log('PASS imaging HTTP: real QIDO/WADO, 2 studies, mismatch, duplicate, download, viewer authorization, CSRF, unlink and audit');
