// <auto-generated />
using System;
using ClinicFlow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicFlow.Migrations
{
    [DbContext(typeof(ClinicDb))]
    [Migration("20260926103151_ImagingLinks")]
    partial class ImagingLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClinicFlow.DemoUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClinicFlow.Imaging.ImagingAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId", "Id");

                    b.ToTable("ImagingAudit");
                });

            modelBuilder.Entity("ClinicFlow.Imaging.ImagingIdentity", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalPatientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("PatientId");

                    b.HasIndex("Source", "ExternalPatientId", "Issuer")
                        .IsUnique();

                    b.ToTable("ImagingIdentity");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            ExternalPatientId = "CF-IMG-001",
                            Issuer = "ClinicFlowDemo",
                            Source = "orthanc-demo"
                        },
                        new
                        {
                            PatientId = 2,
                            ExternalPatientId = "CF-IMG-002",
                            Issuer = "ClinicFlowDemo",
                            Source = "orthanc-demo"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Imaging.ImagingLink", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("StudyInstanceUid")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("LinkedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LinkedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("AppointmentId", "StudyInstanceUid");

                    b.ToTable("ImagingLink");
                });

            modelBuilder.Entity("ClinicFlow.Integration.SyncAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaseToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LeaseToken")
                        .IsUnique();

                    b.HasIndex("MessageId", "Id");

                    b.ToTable("SyncAttempt");
                });

            modelBuilder.Entity("ClinicFlow.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Identifier = "DEMO-001",
                            Name = "林晓（模拟）"
                        },
                        new
                        {
                            Id = 2,
                            Identifier = "DEMO-002",
                            Name = "陈晨（模拟）"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kind = "Consultation",
                            Name = "预约室 A"
                        },
                        new
                        {
                            Id = 2,
                            Kind = "Consultation",
                            Name = "预约室 B"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Scheduling.Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("StartUtc", "Id");

                    b.HasIndex("ResourceId", "StartUtc", "Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ClinicFlow.Scheduling.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId", "Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("ClinicFlow.Scheduling.IdempotencyRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Response")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Idempotency");
                });

            modelBuilder.Entity("ClinicFlow.Scheduling.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastError")
                        .HasColumnType("longtext");

                    b.Property<string>("LeaseToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LeaseUntilUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptUtc");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("ClinicFlow.Scheduling.PrerequisiteTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ClinicFlow.Scheduling.SlotClaim", b =>
                {
                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlotStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("ResourceId", "SlotStartUtc");

                    b.HasIndex("AppointmentId");

                    b.ToTable("SlotClaims");
                });

            modelBuilder.Entity("ClinicFlow.DemoUser", b =>
                {
                    b.HasOne("ClinicFlow.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicFlow.Imaging.ImagingAudit", b =>
                {
                    b.HasOne("ClinicFlow.Scheduling.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicFlow.Imaging.ImagingIdentity", b =>
                {
                    b.HasOne("ClinicFlow.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicFlow.Imaging.ImagingLink", b =>
                {
                    b.HasOne("ClinicFlow.Scheduling.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicFlow.Scheduling.Appointment", b =>
                {
                    b.HasOne("ClinicFlow.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicFlow.Scheduling.PrerequisiteTask", b =>
                {
                    b.HasOne("ClinicFlow.Scheduling.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicFlow.Scheduling.SlotClaim", b =>
                {
                    b.HasOne("ClinicFlow.Scheduling.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
